<?php
/** @var \Nofrixion\Payments\Block\InitiatePaymentResult $block */

xdebug_break();

$paymentRequest = $block->getPaymentRequest();
$order = $block->getOrder();
$messages = $block->getMessages();

echo '<div id="error-details" class="nfPaymentSection">';
echo '<p>An error has occurred processing payment:</p>';
echo 'Order ID: ' . $order->getIncrementId() . '<br/>';
echo 'Payment request ID: ' . $paymentRequest['id'] . '<br/>';
echo '</div>';

echo '<div id="messages" class="nfPaymentSection">';
foreach ($messages as $msg) {
    echo $msg . '<br/>';
}
echo '</div>';
?>

<br/>
<button type="button" class="action primary checkout" onclick="window.location.href='<?php echo $block->getUrl('checkout/cart'); ?>'">
    <span><?php echo __('Return to Cart'); ?></span>
</button>
