<!-- Create card details layout -->
<div>
    <form id="cardPaymentForm" onsubmit="event.preventDefault();">
        <div>
            <label class="nfPrompt">Card number<span className="required">*</span></label>

            <!-- <div> tag where card number secure iFrame will be injected -->
            <div id="cardNumber-container" style="height: 30px; width: 200px"></div>
        </div>
        <div>
            <div>
                <label>Expiry Date <span class="required">*</span></label>
                <div>
                    <input class="nfInput" type="text" id="nf-expiryMonth" placeholder="MM" size="2" maxLength="{2}"
                        inputMode="numeric" />
                    <span class="">/</span>
                    <input class="nfInput" type="text" id="nf-expiryYear" placeholder="YYYY" size="4" maxLength="{4}"
                        inputMode="numeric" />
                </div>
            </div>
            <div>
                <label>Card Code (CVC) <span className="required">*</span></label>

                <!--  <div> tag where card security code secure iFrame will be injected -->
                <div id="cardSecurityCode-container" style="height: 30px; width: 40px"></div>
            </div>
        </div>

        <!-- Call nfpayByCard() method on submit to process card payment -->
        <button class="cardButton" onclick="window.nfpayByCard()" type="submit" name="nf-card-submit">
            Pay by card
        </button>
    </form>
</div>

<!-- Web component in charge of injecting the card number and card security code 
    secure iFrames into their respective containers -->
<nofrixion-card-headless paymentrequestid="<?php echo $paymentRequestId ?>" apiurl="<?php echo $apiUrl ?>"
    cardnumberinputid="cardNumber-container" cardsecuritycodeinputid="cardSecurityCode-container"
    errordivid="error-container">
</nofrixion-card-headless>