<?php
/** @var \Nofrixion\Payments\Block\SubmitPayment $block */
?>

<!-- Embed NoFrixion Pay Element Web Component -->
<nofrixion-pay-element 
    paymentrequestid="<?php echo $block->getPaymentRequestId() ?>"
    apiurl="<?php echo $block->getApiUrl() ?>"
    >
</nofrixion-pay-element>

<br/>
paymentrequestid: <?php echo $block->getPaymentRequestId() ?> <br/>
apiurl: <?php echo $block->getApiUrl() ?>